name: Build
on: pull_request
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest] # [macos-12, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            **/requirements.txt
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          python build/locate_libsodium.py
      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        env:
          PYTHONPATH: "pyipv8;src"
        with:
          nuitka-version: main
          script-name: 'src/run_tribler.py'
          standalone: true
          macos-create-app-bundle: true
          static-libpython: 'auto'
          include-package: 'tribler'
          nofollow-import-to: 'tribler.test_*'
          include-onefile-external-data: 'libsodium*'
          user-package-configuration-file: 'build/nuitka.yml'
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            *.dll
            build/*.bin
            build/*.app/**/*
